title: Alson Lim Chin Meng
#logo: 
description: >
  Status: <strong>Year-1 Student in SIT</strong><br><br>
  Course: <strong>Robotic System</strong><br><br>
  Welcome to my GitHub portfolio showcasing projects and coursework in robotics.
  
show_downloads: false
theme: jekyll-theme-leap day
