title: Alson Lim Chin Meng
#logo: 
description: >
  Status: Year-1 Student in SIT<br>
  Course: Robotic System<br>
  Welcome to my GitHub portfolio showcasing projects and coursework in robotics.
  
show_downloads: false
theme: jekyll-theme-minimal
